### ISSUE TITLE
Check distance between buildings at buildRequest

### ISSUE THREAD

**Issue by JulianSobott** [JulianSobott/Catan#14]
We need to validate, whether the new building is too close to another building
Maybe add implementation to map.is_city_place_free

public boolean is_city_place_available(Vector2i pos){
		for( Vector2i ap: available_city_places) {
			if( ap.x == pos.x && ap.y == pos.y){
				return true;
			}
		}
		return false;
	}

**Comment by erikgoe** [comment]
There might be some other issue. 
I already forced villages/cities to be only build on each second corner on the hexagon (i. a. because the number of building sites will then match the number of fields). I thought this will solve the problem that villages/cities have to be two streets appart, but i missed that the player should be able to build e. g. three streets between two buildings, which will end in an "impossible" corner.

So we might have to rewrite the entire building system for villages/cities to enable building on every corner of a hexagon. 
We can adopt the system for streets which already has building sites with three dimensions.

**Comment by erikgoe** [comment]
Nearly all issues with that are fixed now
